name: go-test
on: [push]
jobs:
  unit-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
      - name: Install dependencies
        run: go get .
      - name: Test
        run: go test -v ./...